import Head from "next/head";
import Image from "next/image";
import React from "react";
import styled from "styled-components";

const Main = styled.main`
	min-height: 100vh;
	display: flex;
	justify-content: center;
	align-items: center;
	width: 100%;
`;

const Button = styled.button`
	cursor: pointer;
	z-index: 1000;
	background-color: #000;
	border: 1px solid #fff;
	border-radius: 5px;
	font-size: 1.4rem;
	padding: 10px 40px;
	text-transform: uppercase;
	border: 1px solid;
	position: relative;
	border: 1px solid transparent;
	box-shadow: 0 0 10px 5px red;
	opacity: ${({ isVisible }) => (isVisible ? 0 : 1)};
`;

const Img = styled.img`
	width: 100%;
	height: 100%;
	object-fit: cover;
	position: absolute;
	top: 0;
	left: 0;
	display: ${({ isVisible }) => (isVisible ? "block" : "none")};
	scale: 0;
	transition: 4s ease-in;
	transition-delay: ${({ delay }) => `${delay}s`};
`;

export default function Home() {
	const [visible, setVisible] = React.useState(false);

	function handleClick() {
		const imgs = document.querySelectorAll("img");

		setTimeout(() => {
			imgs.forEach((item) => {
				item.style.scale = 1;
			});
		}, 1000);
		setVisible(!visible);
	}

	return (
		<div>
			<Head>
				<title>Infinite Images</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
			</Head>

			<Main>
				<Img
					delay={0}
					src="/datingscout-lgC7PQiwwQ0-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={3}
					src="/florian-olivo-_F2HOc1Skk8-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={6}
					src="/greg-rakozy-oMpAz-DN-9I-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={9}
					src="/ilya-orehov-3ZWSDuaE_Go-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={12}
					src="/joshua-coleman-R1OSU00xo78-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={15}
					src="/kevin-ianeselli-ebnlHkqfUHY-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={18}
					src="/nithin-p-john-4j1vF2ZF9Y4-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={21}
					src="/pascal-debrunner-Ap53G_567Dc-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={24}
					src="/patrick-tomasso-5hvn-2WW6rY-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={27}
					src="/piotr-guzik-oCdRcuzy3mo-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Img
					delay={30}
					src="/sangga-rima-roman-selia-3sE3Y_rI700-unsplash.jpg"
					alt=""
					width={1600}
					height={1000}
					isVisible={visible}
				/>
				<Button isVisible={visible} onClick={handleClick}>
					Start
				</Button>
			</Main>
		</div>
	);
}
